# pypi deps:
#   absl-py
#   pycapnp
#   pyzmq
py_binary(
    name = "talker_py",
    srcs = ["talker.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//a17/capnp_msgs:capnp_msgs_py",
        "//a17/dispatch:dispatch_py",
    ],
)

# pypi deps:
#   absl-py
#   pycapnp
#   pyzmq
py_binary(
    name = "listener_py",
    srcs = ["listener.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//a17/capnp_msgs:capnp_msgs_py",
        "//a17/dispatch:dispatch_py",
    ],
)

cc_binary(
    name = "talker",
    srcs = ["talker.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//a17/capnp_msgs",
        "//a17/dispatch",
    ],
)

cc_binary(
    name = "listener",
    srcs = ["listener.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//a17/capnp_msgs",
        "//a17/dispatch",
    ],
)
