name: C++ and Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    # This job runs on your self-hosted runner
    runs-on: self-hosted

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Get runner user and group IDs
      id: get-ids
      run: |
        echo "uid=$(id -u)" >> $GITHUB_OUTPUT
        echo "gid=$(id -g)" >> $GITHUB_OUTPUT

    # - name: Get Bazel version
    #   id: bazel
    #   run: echo "version=$(cat .bazelversion)" >> $GITHUB_OUTPUT
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: a17-tools-dev:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Run CI Script
      run: |
        chmod +x run-ci.sh
        ./run-ci.sh
